# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: oracle_enhanced
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  #database: //localhost:1521/FREE
  database: FREE
  username: AXEL
  password: Chutinhbk123@!
  host: localhost

test:
  <<: *default

production:
  <<: *default

